CREATE TABLE IF NOT EXISTS agent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description CLOB,
    avatar CLOB,
    category VARCHAR(100),
    tags CLOB,
    prompt CLOB,
    preset_questions CLOB,
    status VARCHAR(50) DEFAULT 'draft',
    admin_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_agent_name ON agent (name);
CREATE INDEX IF NOT EXISTS idx_agent_status ON agent (status);
CREATE INDEX IF NOT EXISTS idx_agent_category ON agent (category);
CREATE INDEX IF NOT EXISTS idx_agent_admin_id ON agent (admin_id);

CREATE TABLE IF NOT EXISTS model_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    provider VARCHAR(100) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    model_type VARCHAR(50) NOT NULL,
    base_url VARCHAR(1000),
    api_key VARCHAR(1000),
    temperature DOUBLE,
    max_tokens INT,
    enabled BOOLEAN DEFAULT TRUE,
    description CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_model_config_name ON model_config (name);
CREATE INDEX IF NOT EXISTS idx_model_config_provider ON model_config (provider);
CREATE INDEX IF NOT EXISTS idx_model_config_model_type ON model_config (model_type);
CREATE INDEX IF NOT EXISTS idx_model_config_enabled ON model_config (enabled);

CREATE TABLE IF NOT EXISTS datasource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    db_type VARCHAR(50) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    username VARCHAR(255),
    password VARCHAR(1000),
    database_name VARCHAR(255),
    host VARCHAR(255),
    port INT,
    enabled BOOLEAN DEFAULT TRUE,
    description CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_datasource_name ON datasource (name);
CREATE INDEX IF NOT EXISTS idx_datasource_db_type ON datasource (db_type);
CREATE INDEX IF NOT EXISTS idx_datasource_database_name ON datasource (database_name);
CREATE INDEX IF NOT EXISTS idx_datasource_enabled ON datasource (enabled);

CREATE TABLE IF NOT EXISTS agent_datasource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    datasource_id BIGINT NOT NULL,
    datasource_name VARCHAR(255),
    db_type VARCHAR(50),
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_agent_datasource UNIQUE (agent_id, datasource_id)
);

CREATE INDEX IF NOT EXISTS idx_agent_datasource_agent_id ON agent_datasource (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_datasource_datasource_id ON agent_datasource (datasource_id);
CREATE INDEX IF NOT EXISTS idx_agent_datasource_db_type ON agent_datasource (db_type);
CREATE INDEX IF NOT EXISTS idx_agent_datasource_enabled ON agent_datasource (enabled);

CREATE TABLE IF NOT EXISTS semantic_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datasource_id BIGINT NOT NULL,
    table_name VARCHAR(255) NOT NULL,
    business_name VARCHAR(255) NOT NULL,
    description CLOB,
    synonyms CLOB,
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_datasource_table UNIQUE (datasource_id, table_name)
);

CREATE INDEX IF NOT EXISTS idx_semantic_table_datasource_id ON semantic_table (datasource_id);
CREATE INDEX IF NOT EXISTS idx_semantic_table_enabled ON semantic_table (enabled);

CREATE TABLE IF NOT EXISTS semantic_field (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT NOT NULL,
    datasource_id BIGINT NOT NULL,
    table_name VARCHAR(255) NOT NULL,
    field_name VARCHAR(255) NOT NULL,
    business_name VARCHAR(255) NOT NULL,
    data_type VARCHAR(100),
    description CLOB,
    synonyms CLOB,
    example_value CLOB,
    primary_key BOOLEAN DEFAULT FALSE,
    nullable BOOLEAN DEFAULT TRUE,
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_table_field UNIQUE (table_id, field_name)
);

CREATE INDEX IF NOT EXISTS idx_semantic_field_table_id ON semantic_field (table_id);
CREATE INDEX IF NOT EXISTS idx_semantic_field_datasource_id ON semantic_field (datasource_id);
CREATE INDEX IF NOT EXISTS idx_semantic_field_enabled ON semantic_field (enabled);

CREATE TABLE IF NOT EXISTS semantic_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datasource_id BIGINT NOT NULL,
    source_table_id BIGINT NOT NULL,
    source_table_name VARCHAR(255) NOT NULL,
    source_field_id BIGINT NOT NULL,
    source_field_name VARCHAR(255) NOT NULL,
    target_table_id BIGINT NOT NULL,
    target_table_name VARCHAR(255) NOT NULL,
    target_field_id BIGINT NOT NULL,
    target_field_name VARCHAR(255) NOT NULL,
    relation_type VARCHAR(50) DEFAULT 'logical',
    join_type VARCHAR(50) DEFAULT 'INNER JOIN',
    description CLOB,
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_semantic_relation_datasource_id ON semantic_relation (datasource_id);
CREATE INDEX IF NOT EXISTS idx_semantic_relation_source_table_id ON semantic_relation (source_table_id);
CREATE INDEX IF NOT EXISTS idx_semantic_relation_target_table_id ON semantic_relation (target_table_id);
CREATE INDEX IF NOT EXISTS idx_semantic_relation_enabled ON semantic_relation (enabled);

CREATE TABLE IF NOT EXISTS business_knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content CLOB,
    knowledge_type VARCHAR(50) NOT NULL,
    source_type VARCHAR(50) DEFAULT 'text',
    file_name VARCHAR(500),
    file_path VARCHAR(1000),
    file_size BIGINT,
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_business_knowledge_title ON business_knowledge (title);
CREATE INDEX IF NOT EXISTS idx_business_knowledge_type ON business_knowledge (knowledge_type);
CREATE INDEX IF NOT EXISTS idx_business_knowledge_source_type ON business_knowledge (source_type);
CREATE INDEX IF NOT EXISTS idx_business_knowledge_enabled ON business_knowledge (enabled);

CREATE TABLE IF NOT EXISTS agent_knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    knowledge_id BIGINT NOT NULL,
    knowledge_title VARCHAR(255),
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_agent_knowledge UNIQUE (agent_id, knowledge_id)
);

CREATE INDEX IF NOT EXISTS idx_agent_knowledge_agent_id ON agent_knowledge (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_knowledge_knowledge_id ON agent_knowledge (knowledge_id);
CREATE INDEX IF NOT EXISTS idx_agent_knowledge_enabled ON agent_knowledge (enabled);

CREATE TABLE IF NOT EXISTS knowledge_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id BIGINT NOT NULL,
    chunk_index INT NOT NULL,
    content CLOB,
    embedding_model_config_id BIGINT,
    embedding_dimension INT,
    embedding_vector CLOB,
    embedding_status VARCHAR(50) DEFAULT 'none',
    embedding_error CLOB,
    embedded_at TIMESTAMP,
    enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_knowledge_chunk UNIQUE (knowledge_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_knowledge_id ON knowledge_chunk (knowledge_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_enabled ON knowledge_chunk (enabled);

CREATE TABLE IF NOT EXISTS prompt_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_key VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    scene VARCHAR(100),
    content CLOB NOT NULL,
    version VARCHAR(50) DEFAULT 'v1',
    enabled BOOLEAN DEFAULT TRUE,
    description CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_prompt_key_version UNIQUE (prompt_key, version)
);

CREATE INDEX IF NOT EXISTS idx_prompt_key ON prompt_template (prompt_key);
CREATE INDEX IF NOT EXISTS idx_prompt_scene ON prompt_template (scene);
CREATE INDEX IF NOT EXISTS idx_prompt_enabled ON prompt_template (enabled);

CREATE TABLE IF NOT EXISTS graph_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL UNIQUE,
    session_id VARCHAR(100),
    agent_id BIGINT,
    agent_name VARCHAR(255),
    model_config_id BIGINT,
    model_name VARCHAR(255),
    datasource_id BIGINT,
    datasource_name VARCHAR(255),
    mode VARCHAR(50),
    question CLOB,
    answer CLOB,
    status VARCHAR(50),
    success BOOLEAN,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    duration_ms BIGINT,
    event_count INT,
    failed_node VARCHAR(100),
    error_message CLOB,
    generated_sql CLOB,
    extracted_sql CLOB,
    repaired_sql CLOB,
    validated_sql CLOB,
    sanitized_sql CLOB,
    sql_limited BOOLEAN,
    sql_limit INT,
    sql_result_truncated BOOLEAN,
    sql_query_timeout_seconds INT,
    sql_security_message CLOB,
    row_count INT,
    result_preview_json CLOB,
    recalled_table_count INT,
    recalled_field_count INT,
    recalled_relation_count INT,
    recalled_knowledge_count INT,
    report_title VARCHAR(500),
    report_markdown CLOB,
    chart_type VARCHAR(50),
    report_summary CLOB,
    sql_validation_error CLOB,
    sql_execution_error CLOB,
    python_engine VARCHAR(100),
    python_executed BOOLEAN,
    python_success BOOLEAN,
    python_duration_ms BIGINT,
    python_fallback_used BOOLEAN,
    python_error_message CLOB,
    confirm_required BOOLEAN DEFAULT FALSE,
    confirm_status VARCHAR(50) DEFAULT 'none',
    confirm_sql CLOB,
    confirmed_sql CLOB,
    confirmed_by VARCHAR(100),
    confirmed_at TIMESTAMP,
    canceled_at TIMESTAMP,
    cancel_reason CLOB,
    resume_token VARCHAR(64),
    pending_payload_json CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_graph_run_session_id ON graph_run (session_id);
CREATE INDEX IF NOT EXISTS idx_graph_run_agent_id ON graph_run (agent_id);
CREATE INDEX IF NOT EXISTS idx_graph_run_status ON graph_run (status);
CREATE INDEX IF NOT EXISTS idx_graph_run_created_at ON graph_run (created_at);

CREATE TABLE IF NOT EXISTS graph_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(100),
    event_id VARCHAR(64),
    node_name VARCHAR(100),
    event_type VARCHAR(50),
    status VARCHAR(50),
    message CLOB,
    data_json CLOB,
    error_message CLOB,
    event_time TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_graph_event_run_id ON graph_event (run_id);
CREATE INDEX IF NOT EXISTS idx_graph_event_node_name ON graph_event (node_name);
CREATE INDEX IF NOT EXISTS idx_graph_event_event_type ON graph_event (event_type);
CREATE INDEX IF NOT EXISTS idx_graph_event_status ON graph_event (status);
CREATE INDEX IF NOT EXISTS idx_graph_event_created_at ON graph_event (created_at);
