CREATE TABLE IF NOT EXISTS agent (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description LONGTEXT,
    avatar LONGTEXT,
    category VARCHAR(100),
    tags LONGTEXT,
    prompt LONGTEXT,
    preset_questions LONGTEXT,
    status VARCHAR(50) DEFAULT 'draft',
    admin_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_agent_name (name),
    KEY idx_agent_status (status),
    KEY idx_agent_category (category),
    KEY idx_agent_admin_id (admin_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS model_config (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    provider VARCHAR(100) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    model_type VARCHAR(50) NOT NULL,
    base_url VARCHAR(1000),
    api_key VARCHAR(1000),
    temperature DOUBLE,
    max_tokens INT,
    enabled BOOLEAN DEFAULT 1,
    description LONGTEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_model_config_name (name),
    KEY idx_model_config_provider (provider),
    KEY idx_model_config_model_type (model_type),
    KEY idx_model_config_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS datasource (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    db_type VARCHAR(50) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    username VARCHAR(255),
    password VARCHAR(1000),
    database_name VARCHAR(255),
    host VARCHAR(255),
    port INT,
    enabled BOOLEAN DEFAULT 1,
    description LONGTEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_datasource_name (name),
    KEY idx_datasource_db_type (db_type),
    KEY idx_datasource_database_name (database_name),
    KEY idx_datasource_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_datasource (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    datasource_id BIGINT NOT NULL,
    datasource_name VARCHAR(255),
    db_type VARCHAR(50),
    enabled BOOLEAN DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_agent_datasource (agent_id, datasource_id),
    KEY idx_agent_datasource_agent_id (agent_id),
    KEY idx_agent_datasource_datasource_id (datasource_id),
    KEY idx_agent_datasource_db_type (db_type),
    KEY idx_agent_datasource_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS semantic_table (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    datasource_id BIGINT NOT NULL,
    table_name VARCHAR(255) NOT NULL,
    business_name VARCHAR(255) NOT NULL,
    description LONGTEXT,
    synonyms LONGTEXT,
    enabled BOOLEAN DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_datasource_table (datasource_id, table_name),
    KEY idx_semantic_table_datasource_id (datasource_id),
    KEY idx_semantic_table_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS semantic_field (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    table_id BIGINT NOT NULL,
    datasource_id BIGINT NOT NULL,
    table_name VARCHAR(255) NOT NULL,
    field_name VARCHAR(255) NOT NULL,
    business_name VARCHAR(255) NOT NULL,
    data_type VARCHAR(100),
    description LONGTEXT,
    synonyms LONGTEXT,
    example_value LONGTEXT,
    primary_key BOOLEAN DEFAULT 0,
    nullable BOOLEAN DEFAULT 1,
    enabled BOOLEAN DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_table_field (table_id, field_name),
    KEY idx_semantic_field_table_id (table_id),
    KEY idx_semantic_field_datasource_id (datasource_id),
    KEY idx_semantic_field_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS semantic_relation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    datasource_id BIGINT NOT NULL,
    source_table_id BIGINT NOT NULL,
    source_table_name VARCHAR(255) NOT NULL,
    source_field_id BIGINT NOT NULL,
    source_field_name VARCHAR(255) NOT NULL,
    target_table_id BIGINT NOT NULL,
    target_table_name VARCHAR(255) NOT NULL,
    target_field_id BIGINT NOT NULL,
    target_field_name VARCHAR(255) NOT NULL,
    relation_type VARCHAR(50) DEFAULT 'logical',
    join_type VARCHAR(50) DEFAULT 'INNER JOIN',
    description LONGTEXT,
    enabled TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_semantic_relation_datasource_id (datasource_id),
    KEY idx_semantic_relation_source_table_id (source_table_id),
    KEY idx_semantic_relation_target_table_id (target_table_id),
    KEY idx_semantic_relation_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS business_knowledge (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content LONGTEXT,
    knowledge_type VARCHAR(50) NOT NULL,
    source_type VARCHAR(50) DEFAULT 'text',
    file_name VARCHAR(500),
    file_path VARCHAR(1000),
    file_size BIGINT,
    enabled BOOLEAN DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_business_knowledge_title (title),
    KEY idx_business_knowledge_type (knowledge_type),
    KEY idx_business_knowledge_source_type (source_type),
    KEY idx_business_knowledge_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_knowledge (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    agent_id BIGINT NOT NULL,
    knowledge_id BIGINT NOT NULL,
    knowledge_title VARCHAR(255),
    enabled BOOLEAN DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_agent_knowledge (agent_id, knowledge_id),
    KEY idx_agent_knowledge_agent_id (agent_id),
    KEY idx_agent_knowledge_knowledge_id (knowledge_id),
    KEY idx_agent_knowledge_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS knowledge_chunk (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    knowledge_id BIGINT NOT NULL,
    chunk_index INT NOT NULL,
    content LONGTEXT,
    embedding_model_config_id BIGINT,
    embedding_dimension INT,
    embedding_vector LONGTEXT,
    embedding_status VARCHAR(50) DEFAULT 'none',
    embedding_error TEXT,
    embedded_at TIMESTAMP NULL,
    enabled BOOLEAN DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_knowledge_chunk (knowledge_id, chunk_index),
    KEY idx_knowledge_chunk_knowledge_id (knowledge_id),
    KEY idx_knowledge_chunk_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS prompt_template (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    prompt_key VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    scene VARCHAR(100),
    content LONGTEXT NOT NULL,
    version VARCHAR(50) DEFAULT 'v1',
    enabled BOOLEAN DEFAULT 1,
    description LONGTEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_prompt_key_version (prompt_key, version),
    KEY idx_prompt_key (prompt_key),
    KEY idx_prompt_scene (scene),
    KEY idx_prompt_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS graph_run (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(100),
    agent_id BIGINT,
    agent_name VARCHAR(255),
    model_config_id BIGINT,
    model_name VARCHAR(255),
    datasource_id BIGINT,
    datasource_name VARCHAR(255),
    mode VARCHAR(50),
    question LONGTEXT,
    answer LONGTEXT,
    status VARCHAR(50),
    success BOOLEAN,
    started_at TIMESTAMP NULL,
    finished_at TIMESTAMP NULL,
    duration_ms BIGINT,
    event_count INT,
    failed_node VARCHAR(100),
    error_message LONGTEXT,
    generated_sql LONGTEXT,
    extracted_sql LONGTEXT,
    repaired_sql LONGTEXT,
    validated_sql LONGTEXT,
    sanitized_sql LONGTEXT,
    sql_limited BOOLEAN,
    sql_limit INT,
    sql_result_truncated BOOLEAN,
    sql_query_timeout_seconds INT,
    sql_security_message LONGTEXT,
    row_count INT,
    result_preview_json LONGTEXT,
    recalled_table_count INT,
    recalled_field_count INT,
    recalled_relation_count INT,
    recalled_knowledge_count INT,
    report_title VARCHAR(500),
    report_markdown LONGTEXT,
    chart_type VARCHAR(50),
    report_summary LONGTEXT,
    sql_validation_error LONGTEXT,
    sql_execution_error LONGTEXT,
    python_engine VARCHAR(100),
    python_executed BOOLEAN,
    python_success BOOLEAN,
    python_duration_ms BIGINT,
    python_fallback_used BOOLEAN,
    python_error_message LONGTEXT,
    confirm_required BOOLEAN DEFAULT 0,
    confirm_status VARCHAR(50) DEFAULT 'none',
    confirm_sql LONGTEXT,
    confirmed_sql LONGTEXT,
    confirmed_by VARCHAR(100),
    confirmed_at TIMESTAMP NULL,
    canceled_at TIMESTAMP NULL,
    cancel_reason LONGTEXT,
    resume_token VARCHAR(64),
    pending_payload_json LONGTEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY unique_graph_run_run_id (run_id),
    KEY idx_graph_run_session_id (session_id),
    KEY idx_graph_run_agent_id (agent_id),
    KEY idx_graph_run_status (status),
    KEY idx_graph_run_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS graph_event (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    session_id VARCHAR(100),
    event_id VARCHAR(64),
    node_name VARCHAR(100),
    event_type VARCHAR(50),
    status VARCHAR(50),
    message LONGTEXT,
    data_json LONGTEXT,
    error_message LONGTEXT,
    event_time TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY idx_graph_event_run_id (run_id),
    KEY idx_graph_event_node_name (node_name),
    KEY idx_graph_event_event_type (event_type),
    KEY idx_graph_event_status (status),
    KEY idx_graph_event_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
